Repository malcommac/Owl, pull requests merged in 2019-11, with the labels that each got.

#41 Change CollectionHeaderFooterAdapter, TableSection and TableHeaderFooterAdapter to open
  README.md
  Sources/Owl/Collection/HeaderFooter Adapter/CollectionHeaderFooterAdapter.swift
  Sources/Owl/Table/Header Adapter/TableHeaderFooterAdapter.swift
  Sources/Owl/Table/TableSection.swift
Labels: bug, enhancement

#40 Fix SPM iOS
  Package.swift
Labels: bug

#20 Default implementation for isContentEqual
  Sources/Shared/Protocols/ElementRepresentable.swift
Labels: enhancement
